name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run allTests
    export-report:
      steps:
      - name: Export Report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-mochawesome-reporter
          path: cypress/reports/index.html
          retention-days: 5